yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.post_create, name='post_create'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/',
         views.add_comment, name='add_comment'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/', views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
]

handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=200, blank=True)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Введите текст поста',
    )
    pub_date = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор',
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        verbose_name='Группа',
        related_name='posts',
        blank=True,
        null=True,
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True,
        help_text='Картинка для поста'
    )

    class Meta:
        ordering = ('-pub_date', )
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:settings.MAX_SYMS]


class Comment(models.Model):
    text = models.TextField(
        verbose_name='Комментарий',
        help_text='Введите комментарий'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        verbose_name='Пост',
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        null=True,
        on_delete=models.CASCADE,
        verbose_name='Автор комментария',
        related_name='comments'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации комментария'
    )

    class Meta:
        ordering = ('-created', )
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:settings.MAX_SYMS]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор записей'
    )

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'
        constraints = [models.UniqueConstraint(
            fields=['user', 'author'],
            name='unique_follow')
        ]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea, required=True)

    class Meta:
        model = Post
        fields = ('text', 'group', 'image')
        labels = {
            'text': 'Автор',
            'group': 'Название группы',
            'image': 'Картинка для поста',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Comment, Follow, Group, Post, User


def pagination(posts, request):
    paginator = Paginator(posts, settings.MAX_POSTS)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return page_obj


def index(request):
    posts = Post.objects.select_related('group', 'author')
    page_obj = pagination(posts, request)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.select_related('author')
    page_obj = pagination(posts, request)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.select_related('author')
    page_obj = pagination(posts, request)
    following = (
        request.user.is_authenticated
        and Follow.objects.filter(author=author, user=request.user).exists()
    )
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    comments = Comment.objects.filter(post_id=post.id)
    posts_count = post.author.posts.count()
    context = {
        'post': post,
        'posts_count': posts_count,
        'comments': comments,
        'form': form,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    context = {
        'form': form,
    }
    if not form.is_valid():
        return render(request, 'posts/post_create.html', context)
    post = form.save(commit=False)
    post.author = request.user
    form.save()
    return redirect('posts:profile', post.author)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id)
    context = {
        'form': form,
    }
    return render(request, 'posts/post_create.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(
        author__following__user=request.user).select_related('author')
    page_obj = pagination(posts, request)
    content = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', content)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username=author.username)


@login_required
def profile_unfollow(request, username):
    follower = Follow.objects.filter(
        user=request.user, author__username=username)
    if follower.exists():
        follower.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
  Избранные авторы
{% endblock %}

{% block content %}
{% include 'includes/switcher.html' %}
  {% block header %}
  Избранные авторы
  {% endblock header %}
  {% cache 20 index_page page_obj.number %}
  {% for post in page_obj %}
    {% include 'posts/post_card.html' %}
  {% endfor %}
  {% endcache %}
  {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

{% block title %}
  {{ group.title }}
{% endblock %}

{% block content %}
  {% block header %}
    {{ group.title }}
  {% endblock header %}
  <p>{{ group.description|linebreaks }}</p>
  {% for post in page_obj %}
    {% include 'posts/post_card.html' %}
  {% endfor %}
  {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load cache %}
{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
{% include 'includes/switcher.html' %}
  {% block header %}
    Последние обновления на сайте
  {% endblock header %}
  {% cache 20 index_page page_obj.number %}
  {% for post in page_obj %}
    {% include 'posts/post_card.html' %}
  {% endfor %}
  {% endcache %}
  {% include 'posts/paginator.html' %}
{% endblock %}

yatube/templates/posts/paginator.html
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
          <span class="page-link">{{ i }}</span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/post_card.html
{% load thumbnail %}

<article>
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <p>
    {{ post.text|linebreaks }}
  </p>
  {% if post.group and not group %}   
    <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  {% if not forloop.last %}
    <hr>
  {% endif %}
</article>

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% load user_filters %} 

{% block title %}
  {% if form.instance.post %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">       
          {% if form.instance.post %} 
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          {% if form.instance.post %}     
            <form method="post" 
            enctype="multipart/form-data" 
            action="{% url 'posts:post_edit' post.pk %}">
          {% else %}
            <form method="post" 
            enctype="multipart/form-data" 
            action="{% url 'posts:post_create' %}">
          {% endif %}
          {% csrf_token %}
          {% for field in form %}         
            <div class="form-group row my-3 p-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}                  
                    <span class="required text-danger" >*</span>
                  {% endif %}                  
              </label>
              <div>  
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">  
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}                         
              </div>
            </div>
          {% endfor %}
          <div class="d-flex justify-content-end">
            <button type="submit" class="btn btn-primary">
              {% if form.instance.post %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}               
            </button> 
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}
  Пост: {{ post.text|truncatewords:30 }}
{% endblock %}

{% block content %}
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:'d E Y' }}
        </li>
        {% if post.group %}
          <li class="list-group-item">
            Группа: {{ group.title }}
            <br>
            <a href="{% url 'posts:group_list' post.group.slug %}">
              Все записи группы
            </a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: {{ post.author.get_full_name }}
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span> {{ page_obj.paginator.count }} </span>
        </li>
        <li class="list-group-item">
        <a href="{% url 'posts:profile' post.author.username %}">
          Все посты пользователя
        </a>
        <br><br>
         {% if request.user.is_authenticated %}
            <a href="{% url 'posts:post_edit' post.pk %}">
              Редактировать пост
            </a>
         {% endif %}
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>
        {{ post.text }}
      </p>
    </article>
    {% if request.user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}      
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}
    {% for comment in comments %}
    <div class="media mb-4">
      <div class="media-body">
        <h5 class="mt-0">
          <a href="{% url 'posts:profile' comment.author.username %}">
            {{ comment.author.username }}
          </a>
        </h5>
          <p>
           {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}

{% block title %}
  Профайл пользователя {{ User.username }}
{% endblock %}

{% block content %}
  {% if request.user.is_authenticated %}
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
      {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>
    {% endif %}
  {% endif %}
  {% block header %}
    Все посты пользователя {{ author.get_full_name }}
  {% endblock header %}
  <h3>Всего постов: {{ page_obj.paginator.count }} </h3>   
  {% for post in page_obj %}
    {% include 'posts/post_card.html' %}
  {% endfor %}
  {% include 'posts/paginator.html' %}
{% endblock %}